/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from './home';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/element';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from 'ionic-angular/navigation/nav-controller';
import * as import9 from '../../providers/location-tracker';
import * as import10 from '@angular/core/src/metadata/view';
import * as import11 from '@angular/core/src/linker/component_factory';
import * as import12 from '../../node_modules/ionic-angular/components/toolbar/toolbar.ngfactory';
import * as import13 from '../../node_modules/ionic-angular/components/navbar/navbar.ngfactory';
import * as import14 from '../../node_modules/ionic-angular/components/toolbar/toolbar-title.ngfactory';
import * as import15 from '../../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import16 from '../../node_modules/ionic-angular/components/item/item.ngfactory';
import * as import17 from '@angular/core/src/linker/query_list';
import * as import18 from '../../node_modules/ionic-angular/components/label/label.ngfactory';
import * as import19 from '../../node_modules/@angular/forms/src/directives/ng_model.ngfactory';
import * as import20 from '../../node_modules/@angular/forms/src/directives/ng_control_status.ngfactory';
import * as import21 from '../../node_modules/ionic-angular/components/input/input.ngfactory';
import * as import22 from '../../node_modules/ionic-angular/components/button/button.ngfactory';
import * as import23 from 'ionic-angular/config/config';
import * as import24 from '@angular/core/src/linker/element_ref';
import * as import25 from 'ionic-angular/navigation/view-controller';
import * as import26 from 'ionic-angular/components/app/app';
import * as import27 from 'ionic-angular/components/toolbar/toolbar';
import * as import28 from 'ionic-angular/util/keyboard';
import * as import29 from '@angular/core/src/zone/ng_zone';
import * as import30 from 'ionic-angular/components/tabs/tabs';
import * as import31 from 'ionic-angular/util/form';
import * as import32 from 'ionic-angular/components/item/item-reorder';
import * as import33 from 'ionic-angular/platform/platform';
import * as import34 from 'ionic-angular/components/toolbar/toolbar-title';
import * as import35 from 'ionic-angular/components/navbar/navbar';
import * as import36 from 'ionic-angular/components/label/label';
import * as import37 from '@angular/forms/src/directives/ng_model';
import * as import38 from '@angular/forms/src/directives/ng_control';
import * as import39 from '@angular/forms/src/directives/ng_control_status';
import * as import40 from 'ionic-angular/components/input/input';
import * as import41 from 'ionic-angular/components/item/item';
import * as import42 from 'ionic-angular/components/button/button';
import * as import43 from 'ionic-angular/components/content/content';
export class Wrapper_HomePage {
  context:import0.HomePage;
  changed:boolean;
  constructor(p0:any,p1:any) {
    this.changed = false;
    this.context = new import0.HomePage(p0,p1);
  }
  detectChangesInternal(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    return changed;
  }
}
var renderType_HomePage_Host:import2.RenderComponentType = (null as any);
class _View_HomePage_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _HomePage_0_4:Wrapper_HomePage;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_HomePage_Host0,renderType_HomePage_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.selectOrCreateHostElement('page-home',rootSelector,(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_HomePage0(this.viewUtils,this.injector(0),this._appEl_0);
    this._HomePage_0_4 = new Wrapper_HomePage(this.parentInjector.get(import8.NavController),this.parentInjector.get(import9.LocationTracker));
    this._appEl_0.initComponent(this._HomePage_0_4.context,([] as any[]),compView_0);
    compView_0.create(this._HomePage_0_4.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.HomePage) && (0 === requestNodeIndex))) { return this._HomePage_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._HomePage_0_4.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_HomePage_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  if ((renderType_HomePage_Host === (null as any))) { (renderType_HomePage_Host = viewUtils.createRenderComponentType('',0,import10.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_HomePage_Host0(viewUtils,parentInjector,declarationEl);
}
export const HomePageNgFactory:import11.ComponentFactory<import0.HomePage> = new import11.ComponentFactory<import0.HomePage>('page-home',viewFactory_HomePage_Host0,import0.HomePage);
const styles_HomePage:any[] = ['.title[_ngcontent-%COMP%]{\n    text-align:center;\n  }\n  .bluelabel[_ngcontent-%COMP%]{\n    color:blue;\n    text-align :left;\n  }'];
var renderType_HomePage:import2.RenderComponentType = (null as any);
class _View_HomePage0 extends import1.AppView<import0.HomePage> {
  _el_0:any;
  _Header_0_3:import12.Wrapper_Header;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import3.AppElement;
  _Navbar_2_4:import13.Wrapper_Navbar;
  _text_3:any;
  _el_4:any;
  /*private*/ _appEl_4:import3.AppElement;
  _ToolbarTitle_4_4:import14.Wrapper_ToolbarTitle;
  _text_5:any;
  _text_6:any;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  /*private*/ _appEl_9:import3.AppElement;
  _Content_9_4:import15.Wrapper_Content;
  _text_10:any;
  _el_11:any;
  _text_12:any;
  _text_13:any;
  _el_14:any;
  _text_15:any;
  _text_16:any;
  _el_17:any;
  _text_18:any;
  _text_19:any;
  _el_20:any;
  /*private*/ _appEl_20:import3.AppElement;
  _Item_20_4:import16.Wrapper_Item;
  _ItemContent_20_5:import16.Wrapper_ItemContent;
  _query_Label_20_0:import17.QueryList<any>;
  _query_Button_20_1:import17.QueryList<any>;
  _query_Icon_20_2:import17.QueryList<any>;
  _text_21:any;
  _el_22:any;
  _Label_22_3:import18.Wrapper_Label;
  _text_23:any;
  _text_24:any;
  _el_25:any;
  /*private*/ _appEl_25:import3.AppElement;
  _NgModel_25_4:import19.Wrapper_NgModel;
  _NgControl_25_5:any;
  _NgControlStatus_25_6:import20.Wrapper_NgControlStatus;
  _TextInput_25_7:import21.Wrapper_TextInput;
  _text_26:any;
  _text_27:any;
  _el_28:any;
  /*private*/ _appEl_28:import3.AppElement;
  _Item_28_4:import16.Wrapper_Item;
  _ItemContent_28_5:import16.Wrapper_ItemContent;
  _query_Label_28_0:import17.QueryList<any>;
  _query_Button_28_1:import17.QueryList<any>;
  _query_Icon_28_2:import17.QueryList<any>;
  _text_29:any;
  _el_30:any;
  /*private*/ _appEl_30:import3.AppElement;
  _Button_30_4:import22.Wrapper_Button;
  _text_31:any;
  _text_32:any;
  _el_33:any;
  /*private*/ _appEl_33:import3.AppElement;
  _Button_33_4:import22.Wrapper_Button;
  _text_34:any;
  _text_35:any;
  _text_36:any;
  _el_37:any;
  /*private*/ _appEl_37:import3.AppElement;
  _Item_37_4:import16.Wrapper_Item;
  _ItemContent_37_5:import16.Wrapper_ItemContent;
  _query_Label_37_0:import17.QueryList<any>;
  _query_Button_37_1:import17.QueryList<any>;
  _query_Icon_37_2:import17.QueryList<any>;
  _text_38:any;
  _el_39:any;
  _text_40:any;
  _text_41:any;
  _el_42:any;
  _text_43:any;
  _text_44:any;
  _el_45:any;
  _text_46:any;
  _text_47:any;
  _text_48:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_10:any;
  /*private*/ _expr_11:any;
  /*private*/ _expr_19:any;
  /*private*/ _expr_20:any;
  /*private*/ _expr_21:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_HomePage0,renderType_HomePage,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'ion-header',(null as any));
    this._Header_0_3 = new import12.Wrapper_Header(this.parentInjector.get(import23.Config),new import24.ElementRef(this._el_0),this.renderer,this.parentInjector.get(import25.ViewController,(null as any)));
    this._text_1 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'ion-navbar',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','title toolbar');
    this.renderer.setElementAttribute(this._el_2,'color','secondary');
    this._appEl_2 = new import3.AppElement(2,0,this,this._el_2);
    var compView_2:any = import13.viewFactory_Navbar0(this.viewUtils,this.injector(2),this._appEl_2);
    this._Navbar_2_4 = new import13.Wrapper_Navbar(this.parentInjector.get(import26.App),this.parentInjector.get(import25.ViewController,(null as any)),this.parentInjector.get(import8.NavController,(null as any)),this.parentInjector.get(import23.Config),new import24.ElementRef(this._el_2),this.renderer);
    this._appEl_2.initComponent(this._Navbar_2_4.context,([] as any[]),compView_2);
    this._text_3 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_4 = this.renderer.createElement((null as any),'ion-title',(null as any));
    this._appEl_4 = new import3.AppElement(4,2,this,this._el_4);
    var compView_4:any = import14.viewFactory_ToolbarTitle0(this.viewUtils,this.injector(4),this._appEl_4);
    this._ToolbarTitle_4_4 = new import14.Wrapper_ToolbarTitle(this.parentInjector.get(import23.Config),new import24.ElementRef(this._el_4),this.renderer,this.parentInjector.get(import27.Toolbar,(null as any)),this._Navbar_2_4.context);
    this._appEl_4.initComponent(this._ToolbarTitle_4_4.context,([] as any[]),compView_4);
    this._text_5 = this.renderer.createText((null as any),'\n      Smart city bus - Location Tracker\n    ',(null as any));
    compView_4.create(this._ToolbarTitle_4_4.context,[([] as any[]).concat([this._text_5])],(null as any));
    this._text_6 = this.renderer.createText((null as any),'\n  ',(null as any));
    compView_2.create(this._Navbar_2_4.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_3,
        this._el_4,
        this._text_6
      ]
      )
    ]
    ,(null as any));
    this._text_7 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_8 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_9 = this.renderer.createElement(parentRenderNode,'ion-content',(null as any));
    this._appEl_9 = new import3.AppElement(9,(null as any),this,this._el_9);
    var compView_9:any = import15.viewFactory_Content0(this.viewUtils,this.injector(9),this._appEl_9);
    this._Content_9_4 = new import15.Wrapper_Content(this.parentInjector.get(import23.Config),new import24.ElementRef(this._el_9),this.renderer,this.parentInjector.get(import26.App),this.parentInjector.get(import28.Keyboard),this.parentInjector.get(import29.NgZone),this.parentInjector.get(import25.ViewController,(null as any)),this.parentInjector.get(import30.Tabs,(null as any)));
    this._appEl_9.initComponent(this._Content_9_4.context,([] as any[]),compView_9);
    this._text_10 = this.renderer.createText((null as any),'\n\n  ',(null as any));
    this._el_11 = this.renderer.createElement((null as any),'p',(null as any));
    this.renderer.setElementAttribute(this._el_11,'class','bluelabel');
    this.renderer.setElementAttribute(this._el_11,'fixed','');
    this._text_12 = this.renderer.createText(this._el_11,'Enter the unique Trip ID before starting the trip.',(null as any));
    this._text_13 = this.renderer.createText((null as any),'\n\n  ',(null as any));
    this._el_14 = this.renderer.createElement((null as any),'p',(null as any));
    this.renderer.setElementAttribute(this._el_14,'class','bluelabel');
    this.renderer.setElementAttribute(this._el_14,'fixed','');
    this._text_15 = this.renderer.createText(this._el_14,'Enable tracking for the Trip ID by clicking Start button.',(null as any));
    this._text_16 = this.renderer.createText((null as any),'\n\n  ',(null as any));
    this._el_17 = this.renderer.createElement((null as any),'p',(null as any));
    this.renderer.setElementAttribute(this._el_17,'class','bluelabel');
    this.renderer.setElementAttribute(this._el_17,'fixed','');
    this._text_18 = this.renderer.createText(this._el_17,'End the trip by clicking Stop button. ',(null as any));
    this._text_19 = this.renderer.createText((null as any),'\n\n  ',(null as any));
    this._el_20 = this.renderer.createElement((null as any),'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_20,'class','item item-block');
    this._appEl_20 = new import3.AppElement(20,9,this,this._el_20);
    var compView_20:any = import16.viewFactory_Item0(this.viewUtils,this.injector(20),this._appEl_20);
    this._Item_20_4 = new import16.Wrapper_Item(this.parentInjector.get(import31.Form),this.parentInjector.get(import23.Config),new import24.ElementRef(this._el_20),this.renderer,this.parentInjector.get(import32.ItemReorder,(null as any)));
    this._ItemContent_20_5 = new import16.Wrapper_ItemContent();
    this._query_Label_20_0 = new import17.QueryList<any>();
    this._query_Button_20_1 = new import17.QueryList<any>();
    this._query_Icon_20_2 = new import17.QueryList<any>();
    this._appEl_20.initComponent(this._Item_20_4.context,([] as any[]),compView_20);
    this._text_21 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_22 = this.renderer.createElement((null as any),'ion-label',(null as any));
    this.renderer.setElementAttribute(this._el_22,'class','bluelabel');
    this.renderer.setElementAttribute(this._el_22,'fixed','');
    this._Label_22_3 = new import18.Wrapper_Label(this.parentInjector.get(import23.Config),new import24.ElementRef(this._el_22),this.renderer,(null as any),(null as any),'',(null as any));
    this._text_23 = this.renderer.createText(this._el_22,'Trip Id:',(null as any));
    this._text_24 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_25 = this.renderer.createElement((null as any),'ion-input',(null as any));
    this.renderer.setElementAttribute(this._el_25,'type','text');
    this._appEl_25 = new import3.AppElement(25,20,this,this._el_25);
    var compView_25:any = import21.viewFactory_TextInput0(this.viewUtils,this.injector(25),this._appEl_25);
    this._NgModel_25_4 = new import19.Wrapper_NgModel((null as any),(null as any),(null as any),(null as any));
    this._NgControl_25_5 = this._NgModel_25_4.context;
    this._NgControlStatus_25_6 = new import20.Wrapper_NgControlStatus(this._NgControl_25_5);
    this._TextInput_25_7 = new import21.Wrapper_TextInput(this.parentInjector.get(import23.Config),this.parentInjector.get(import31.Form),this._Item_20_4.context,this.parentInjector.get(import26.App),this.parentInjector.get(import33.Platform),new import24.ElementRef(this._el_25),this.renderer,this._Content_9_4.context,this.parentInjector.get(import8.NavController,(null as any)),this._NgControl_25_5);
    this._appEl_25.initComponent(this._TextInput_25_7.context,([] as any[]),compView_25);
    compView_25.create(this._TextInput_25_7.context,([] as any[]),(null as any));
    this._text_26 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._query_Label_20_0.reset([this._Label_22_3.context]);
    this._Item_20_4.context.contentLabel = this._query_Label_20_0.first;
    compView_20.create(this._Item_20_4.context,[
      ([] as any[]),
      ([] as any[]).concat([this._el_22]),
      ([] as any[]).concat([
        this._text_21,
        this._text_24,
        this._text_26
      ]
      ),
      ([] as any[]).concat([this._el_25]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_27 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._el_28 = this.renderer.createElement((null as any),'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_28,'class','item item-block');
    this._appEl_28 = new import3.AppElement(28,9,this,this._el_28);
    var compView_28:any = import16.viewFactory_Item0(this.viewUtils,this.injector(28),this._appEl_28);
    this._Item_28_4 = new import16.Wrapper_Item(this.parentInjector.get(import31.Form),this.parentInjector.get(import23.Config),new import24.ElementRef(this._el_28),this.renderer,this.parentInjector.get(import32.ItemReorder,(null as any)));
    this._ItemContent_28_5 = new import16.Wrapper_ItemContent();
    this._query_Label_28_0 = new import17.QueryList<any>();
    this._query_Button_28_1 = new import17.QueryList<any>();
    this._query_Icon_28_2 = new import17.QueryList<any>();
    this._appEl_28.initComponent(this._Item_28_4.context,([] as any[]),compView_28);
    this._text_29 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_30 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_30,'color','secondary');
    this.renderer.setElementAttribute(this._el_30,'full','');
    this.renderer.setElementAttribute(this._el_30,'ion-button','');
    this.renderer.setElementAttribute(this._el_30,'primary','');
    this._appEl_30 = new import3.AppElement(30,28,this,this._el_30);
    var compView_30:any = import22.viewFactory_Button0(this.viewUtils,this.injector(30),this._appEl_30);
    this._Button_30_4 = new import22.Wrapper_Button((null as any),'',this.parentInjector.get(import23.Config),new import24.ElementRef(this._el_30),this.renderer);
    this._appEl_30.initComponent(this._Button_30_4.context,([] as any[]),compView_30);
    this._text_31 = this.renderer.createText((null as any),'Start Tracking',(null as any));
    compView_30.create(this._Button_30_4.context,[([] as any[]).concat([this._text_31])],(null as any));
    this._text_32 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_33 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_33,'color','danger');
    this.renderer.setElementAttribute(this._el_33,'full','');
    this.renderer.setElementAttribute(this._el_33,'ion-button','');
    this.renderer.setElementAttribute(this._el_33,'primary','');
    this._appEl_33 = new import3.AppElement(33,28,this,this._el_33);
    var compView_33:any = import22.viewFactory_Button0(this.viewUtils,this.injector(33),this._appEl_33);
    this._Button_33_4 = new import22.Wrapper_Button((null as any),'',this.parentInjector.get(import23.Config),new import24.ElementRef(this._el_33),this.renderer);
    this._appEl_33.initComponent(this._Button_33_4.context,([] as any[]),compView_33);
    this._text_34 = this.renderer.createText((null as any),'Stop Tracking',(null as any));
    compView_33.create(this._Button_33_4.context,[([] as any[]).concat([this._text_34])],(null as any));
    this._text_35 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._query_Label_28_0.reset(([] as any[]));
    this._Item_28_4.context.contentLabel = this._query_Label_28_0.first;
    compView_28.create(this._Item_28_4.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_29,
        this._el_30,
        this._text_32,
        this._el_33,
        this._text_35
      ]
      ),
      ([] as any[]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_36 = this.renderer.createText((null as any),'\n\n  ',(null as any));
    this._el_37 = this.renderer.createElement((null as any),'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_37,'class','item item-block');
    this._appEl_37 = new import3.AppElement(37,9,this,this._el_37);
    var compView_37:any = import16.viewFactory_Item0(this.viewUtils,this.injector(37),this._appEl_37);
    this._Item_37_4 = new import16.Wrapper_Item(this.parentInjector.get(import31.Form),this.parentInjector.get(import23.Config),new import24.ElementRef(this._el_37),this.renderer,this.parentInjector.get(import32.ItemReorder,(null as any)));
    this._ItemContent_37_5 = new import16.Wrapper_ItemContent();
    this._query_Label_37_0 = new import17.QueryList<any>();
    this._query_Button_37_1 = new import17.QueryList<any>();
    this._query_Icon_37_2 = new import17.QueryList<any>();
    this._appEl_37.initComponent(this._Item_37_4.context,([] as any[]),compView_37);
    this._text_38 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_39 = this.renderer.createElement((null as any),'p',(null as any));
    this.renderer.setElementAttribute(this._el_39,'class','bluelabel');
    this.renderer.setElementAttribute(this._el_39,'fixed','');
    this._text_40 = this.renderer.createText(this._el_39,'',(null as any));
    this._text_41 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_42 = this.renderer.createElement((null as any),'p',(null as any));
    this.renderer.setElementAttribute(this._el_42,'class','bluelabel');
    this.renderer.setElementAttribute(this._el_42,'fixed','');
    this._text_43 = this.renderer.createText(this._el_42,'',(null as any));
    this._text_44 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_45 = this.renderer.createElement((null as any),'pre',(null as any));
    this._text_46 = this.renderer.createText(this._el_45,'',(null as any));
    this._text_47 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._query_Label_37_0.reset(([] as any[]));
    this._Item_37_4.context.contentLabel = this._query_Label_37_0.first;
    compView_37.create(this._Item_37_4.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_38,
        this._el_39,
        this._text_41,
        this._el_42,
        this._text_44,
        this._el_45,
        this._text_47
      ]
      ),
      ([] as any[]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_48 = this.renderer.createText((null as any),'\n\n',(null as any));
    compView_9.create(this._Content_9_4.context,[
      ([] as any[]),
      ([] as any[]).concat([
        this._text_10,
        this._el_11,
        this._text_13,
        this._el_14,
        this._text_16,
        this._el_17,
        this._text_19,
        this._el_20,
        this._text_27,
        this._el_28,
        this._text_36,
        this._el_37,
        this._text_48
      ]
      ),
      ([] as any[])
    ]
    ,(null as any));
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_25,'ngModelChange',this.eventHandler(this._handle_ngModelChange_25_0.bind(this)));
    const subscription_0:any = this._NgModel_25_4.context.update.subscribe(this.eventHandler(this._handle_ngModelChange_25_0.bind(this)));
    this._expr_6 = import7.UNINITIALIZED;
    this._expr_7 = import7.UNINITIALIZED;
    this._expr_8 = import7.UNINITIALIZED;
    this._expr_9 = import7.UNINITIALIZED;
    this._expr_10 = import7.UNINITIALIZED;
    this._expr_11 = import7.UNINITIALIZED;
    var disposable_1:Function = this.renderer.listen(this._el_30,'click',this.eventHandler(this._handle_click_30_0.bind(this)));
    var disposable_2:Function = this.renderer.listen(this._el_33,'click',this.eventHandler(this._handle_click_33_0.bind(this)));
    this._expr_19 = import7.UNINITIALIZED;
    this._expr_20 = import7.UNINITIALIZED;
    this._expr_21 = import7.UNINITIALIZED;
    this.init(([] as any[]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._el_22,
      this._text_23,
      this._text_24,
      this._el_25,
      this._text_26,
      this._text_27,
      this._el_28,
      this._text_29,
      this._el_30,
      this._text_31,
      this._text_32,
      this._el_33,
      this._text_34,
      this._text_35,
      this._text_36,
      this._el_37,
      this._text_38,
      this._el_39,
      this._text_40,
      this._text_41,
      this._el_42,
      this._text_43,
      this._text_44,
      this._el_45,
      this._text_46,
      this._text_47,
      this._text_48
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2
    ]
    ,[subscription_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import34.ToolbarTitle) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 5)))) { return this._ToolbarTitle_4_4.context; }
    if (((token === import35.Navbar) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 6)))) { return this._Navbar_2_4.context; }
    if (((token === import27.Header) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._Header_0_3.context; }
    if (((token === import36.Label) && ((22 <= requestNodeIndex) && (requestNodeIndex <= 23)))) { return this._Label_22_3.context; }
    if (((token === import37.NgModel) && (25 === requestNodeIndex))) { return this._NgModel_25_4.context; }
    if (((token === import38.NgControl) && (25 === requestNodeIndex))) { return this._NgControl_25_5; }
    if (((token === import39.NgControlStatus) && (25 === requestNodeIndex))) { return this._NgControlStatus_25_6.context; }
    if (((token === import40.TextInput) && (25 === requestNodeIndex))) { return this._TextInput_25_7.context; }
    if (((token === import41.Item) && ((20 <= requestNodeIndex) && (requestNodeIndex <= 26)))) { return this._Item_20_4.context; }
    if (((token === import41.ItemContent) && ((20 <= requestNodeIndex) && (requestNodeIndex <= 26)))) { return this._ItemContent_20_5.context; }
    if (((token === import42.Button) && ((30 <= requestNodeIndex) && (requestNodeIndex <= 31)))) { return this._Button_30_4.context; }
    if (((token === import42.Button) && ((33 <= requestNodeIndex) && (requestNodeIndex <= 34)))) { return this._Button_33_4.context; }
    if (((token === import41.Item) && ((28 <= requestNodeIndex) && (requestNodeIndex <= 35)))) { return this._Item_28_4.context; }
    if (((token === import41.ItemContent) && ((28 <= requestNodeIndex) && (requestNodeIndex <= 35)))) { return this._ItemContent_28_5.context; }
    if (((token === import41.Item) && ((37 <= requestNodeIndex) && (requestNodeIndex <= 47)))) { return this._Item_37_4.context; }
    if (((token === import41.ItemContent) && ((37 <= requestNodeIndex) && (requestNodeIndex <= 47)))) { return this._ItemContent_37_5.context; }
    if (((token === import43.Content) && ((9 <= requestNodeIndex) && (requestNodeIndex <= 48)))) { return this._Content_9_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._Header_0_3.detectChangesInternal(this,this._el_0,throwOnChange);
    const currVal_0:any = 'secondary';
    this._Navbar_2_4.check_color(currVal_0,throwOnChange,false);
    this._Navbar_2_4.detectChangesInternal(this,this._el_2,throwOnChange);
    if (this._ToolbarTitle_4_4.detectChangesInternal(this,this._el_4,throwOnChange)) { this._appEl_4.componentView.markAsCheckOnce(); }
    if (this._Content_9_4.detectChangesInternal(this,this._el_9,throwOnChange)) { this._appEl_9.componentView.markAsCheckOnce(); }
    if (this._Item_20_4.detectChangesInternal(this,this._el_20,throwOnChange)) { this._appEl_20.componentView.markAsCheckOnce(); }
    this._ItemContent_20_5.detectChangesInternal(this,this._el_20,throwOnChange);
    this._Label_22_3.detectChangesInternal(this,this._el_22,throwOnChange);
    const currVal_5:any = this.context.locationTracker.txtTrip;
    this._NgModel_25_4.check_model(currVal_5,throwOnChange,false);
    this._NgModel_25_4.detectChangesInternal(this,this._el_25,throwOnChange);
    this._NgControlStatus_25_6.detectChangesInternal(this,this._el_25,throwOnChange);
    const currVal_12:any = 'text';
    this._TextInput_25_7.check_type(currVal_12,throwOnChange,false);
    this._TextInput_25_7.detectChangesInternal(this,this._el_25,throwOnChange);
    if (this._Item_28_4.detectChangesInternal(this,this._el_28,throwOnChange)) { this._appEl_28.componentView.markAsCheckOnce(); }
    this._ItemContent_28_5.detectChangesInternal(this,this._el_28,throwOnChange);
    const currVal_14:any = '';
    this._Button_30_4.check_full(currVal_14,throwOnChange,false);
    const currVal_15:any = 'secondary';
    this._Button_30_4.check_color(currVal_15,throwOnChange,false);
    if (this._Button_30_4.detectChangesInternal(this,this._el_30,throwOnChange)) { this._appEl_30.componentView.markAsCheckOnce(); }
    const currVal_17:any = '';
    this._Button_33_4.check_full(currVal_17,throwOnChange,false);
    const currVal_18:any = 'danger';
    this._Button_33_4.check_color(currVal_18,throwOnChange,false);
    if (this._Button_33_4.detectChangesInternal(this,this._el_33,throwOnChange)) { this._appEl_33.componentView.markAsCheckOnce(); }
    if (this._Item_37_4.detectChangesInternal(this,this._el_37,throwOnChange)) { this._appEl_37.componentView.markAsCheckOnce(); }
    this._ItemContent_37_5.detectChangesInternal(this,this._el_37,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_20_1.dirty) {
        this._query_Button_20_1.reset(([] as any[]));
        this._Item_20_4.context._buttons = this._query_Button_20_1;
        this._query_Button_20_1.notifyOnChanges();
      }
      if (this._query_Icon_20_2.dirty) {
        this._query_Icon_20_2.reset(([] as any[]));
        this._Item_20_4.context._icons = this._query_Icon_20_2;
        this._query_Icon_20_2.notifyOnChanges();
      }
      if (this._query_Button_28_1.dirty) {
        this._query_Button_28_1.reset([
          this._Button_30_4.context,
          this._Button_33_4.context
        ]
        );
        this._Item_28_4.context._buttons = this._query_Button_28_1;
        this._query_Button_28_1.notifyOnChanges();
      }
      if (this._query_Icon_28_2.dirty) {
        this._query_Icon_28_2.reset(([] as any[]));
        this._Item_28_4.context._icons = this._query_Icon_28_2;
        this._query_Icon_28_2.notifyOnChanges();
      }
      if (this._query_Button_37_1.dirty) {
        this._query_Button_37_1.reset(([] as any[]));
        this._Item_37_4.context._buttons = this._query_Button_37_1;
        this._query_Button_37_1.notifyOnChanges();
      }
      if (this._query_Icon_37_2.dirty) {
        this._query_Icon_37_2.reset(([] as any[]));
        this._Item_37_4.context._icons = this._query_Icon_37_2;
        this._query_Icon_37_2.notifyOnChanges();
      }
      this._TextInput_25_7.context.ngAfterContentChecked();
      if ((this.numberOfChecks === 0)) { this._Item_20_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_30_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_33_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_28_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_37_4.context.ngAfterContentInit(); }
    }
    const currVal_1:any = this._Navbar_2_4.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementProperty(this._el_2,'hidden',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = this._Navbar_2_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementClass(this._el_2,'statusbar-padding',currVal_2);
      this._expr_2 = currVal_2;
    }
    const currVal_3:any = this._Content_9_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setElementClass(this._el_9,'statusbar-padding',currVal_3);
      this._expr_3 = currVal_3;
    }
    const currVal_6:any = this._NgControlStatus_25_6.context.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setElementClass(this._el_25,'ng-untouched',currVal_6);
      this._expr_6 = currVal_6;
    }
    const currVal_7:any = this._NgControlStatus_25_6.context.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setElementClass(this._el_25,'ng-touched',currVal_7);
      this._expr_7 = currVal_7;
    }
    const currVal_8:any = this._NgControlStatus_25_6.context.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setElementClass(this._el_25,'ng-pristine',currVal_8);
      this._expr_8 = currVal_8;
    }
    const currVal_9:any = this._NgControlStatus_25_6.context.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this.renderer.setElementClass(this._el_25,'ng-dirty',currVal_9);
      this._expr_9 = currVal_9;
    }
    const currVal_10:any = this._NgControlStatus_25_6.context.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this.renderer.setElementClass(this._el_25,'ng-valid',currVal_10);
      this._expr_10 = currVal_10;
    }
    const currVal_11:any = this._NgControlStatus_25_6.context.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this.renderer.setElementClass(this._el_25,'ng-invalid',currVal_11);
      this._expr_11 = currVal_11;
    }
    const currVal_19:any = import4.interpolate(1,'Current Latitude: ',this.context.locationTracker.lat,'');
    if (import4.checkBinding(throwOnChange,this._expr_19,currVal_19)) {
      this.renderer.setText(this._text_40,currVal_19);
      this._expr_19 = currVal_19;
    }
    const currVal_20:any = import4.interpolate(1,'Current Longitude: ',this.context.locationTracker.lng,'');
    if (import4.checkBinding(throwOnChange,this._expr_20,currVal_20)) {
      this.renderer.setText(this._text_43,currVal_20);
      this._expr_20 = currVal_20;
    }
    const currVal_21:any = import4.interpolate(1,'',this.context.locationTracker.serverRes,'');
    if (import4.checkBinding(throwOnChange,this._expr_21,currVal_21)) {
      this.renderer.setText(this._text_46,currVal_21);
      this._expr_21 = currVal_21;
    }
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Navbar_2_4.context.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this._NgModel_25_4.context.ngOnDestroy();
    this._TextInput_25_7.context.ngOnDestroy();
    this._Content_9_4.context.ngOnDestroy();
  }
  private _handle_ngModelChange_25_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.locationTracker.txtTrip = $event)) !== false);
    return (true && pd_0);
  }
  private _handle_click_30_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.start()) !== false);
    return (true && pd_0);
  }
  private _handle_click_33_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.stop()) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_HomePage0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<import0.HomePage> {
  if ((renderType_HomePage === (null as any))) { (renderType_HomePage = viewUtils.createRenderComponentType('',0,import10.ViewEncapsulation.Emulated,styles_HomePage,{})); }
  return new _View_HomePage0(viewUtils,parentInjector,declarationEl);
}